name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repo
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar apktool
        run: |
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O apktool.jar
          sudo wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O /usr/local/bin/apktool
          sudo chmod +x /usr/local/bin/apktool
          sudo mv apktool.jar /usr/local/bin/apktool.jar

      - name: Build
        run: |
          cd .
          apktool b . -o RavenCity-unsigned.apk

      - name: Assinar APK
        run: |
          wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar -O signer.jar
          java -jar signer.jar --apks RavenCity-unsigned.apk

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: RavenCity-apk
          path: |
            *aligned*.apk
            *signed*.apk
            RavenCity-unsigned.apk
